### ISSUE TITLE
Name of exact algorithm?

### ISSUE THREAD

**Issue by ohtangza** [preston/alignment#1]
Hello, thanks for great work.

I'm planning to implement an app with sequence alignment and your package looks great!

Can I ask, which algorithm you implements?
(I'm a quite beginner for sequence alignment.)

**Comment by preston** [comment]
Honestly I don't recall the specific name off hand.. it's just a generic dynamic programming approach that walks the matrix, the basis of which seems pretty common.

**Comment by ohtangza** [comment]
I took a look at the code, and it was the basic implementation of dynamic programming approach as you mentioned. Thanks for your answer.
